# Appveyor configuration template for Rust using rustup for Rust installation
# https://github.com/starkat99/appveyor-rust

os: Visual Studio 2017

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: i686-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - appveyor DownloadFile https://raw.githubusercontent.com/opentk/opentk/master/install-opengl.ps1 -FileName install-opengl.ps1
  - "powershell ./install-opengl.ps1"

build_script:
  - cargo build --release --verbose --bin league_of_steel
  - cargo build --verbose --all

test_script:
  - cargo test --verbose --all --exclude testlib
  - cargo test --verbose -p testlib -- --test-threads=1

on_finish:
  - "powershell ./install-opengl.ps1 uninstall"
