# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    curl -sSf -o rustup-init.exe https://win.rustup.rs
    rustup-init.exe -y --default-toolchain x86_64-pc-windows-msvc
    echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    rustc -vV
    cargo -vV
  displayName: 'Install rust'

- script: |
    curl -sSf -o install-opengl.ps1 https://raw.githubusercontent.com/opentk/opentk/master/install-opengl.ps1
    powershell ./install-opengl.ps1
  displayName: 'Install OpenGL'

- script: |
    cargo build --verbose --all
  displayName: 'Build'

- script: |
    cargo test --verbose --all --exclude testlib
    cargo test --verbose -p testlib -- --test-threads=1
  displayName: 'Test'
